### ISSUE TITLE
左メニュー欄の削除

### ISSUE THREAD

**Issue by hirosejn** [hirosejn/HJN#8]
## [左メニュー欄の削除](https://github.com/hirosejn/HJN/projects/2#card-1950401)
左側のメニュー欄の機能を、メニューバーなどに移植する
- グラフ表示領域を大きくとれるようにするため
- 将来、下段の複数表示対応や、htmlファイルの制約を減らすことを考慮した機能変更

## 変更点
- [x] 2017/02/26 Legend表示位置を中央に移動、ラベル幅指定
- [x] 2017/03/06 表題「TAT kig duver(ver)」上段メニューバーの上に移動
- [x] 2017/03/06 メッセージエリアを上段メニューバーの上に移動
- [x] 2017/03/06 balloon plotsの削除
  - [x] 2017/03/06 copyボタンのコピー機能を、ファイルダウンロード機能に変更 #2 
  - [x] 2017/03/05 copyボタンのplotsクリア機能を、Plotsエリアのclearボタンに変更
- [x] 2017/03/05 sliderの削除
  - [x] 2017/03/05 ±秒指定機能を、Plotsエリアに移動
  - [x] 2017/03/05 copy dataボタン機能を、menu barのFile/download graph data に移植 #2 
- [x] 2017/03/05 concurrent transactionsの copy機能を、menu barのFile/download conc log rows に移植 #2 
- [x] 2017/03/06 下段表示データ選択機能を、メニューに移動 #4 

### 関連課題
- #2 [ファイルダウンロード機能追加](https://github.com/hirosejn/HJN/projects/2#card-1947949) 
クリップボードコピー機能をメニューバーに移動
- #4 [Legend表示機能移植](https://github.com/hirosejn/HJN/projects/2#card-1948379)
メニュー(View)に移動

**Comment by hirosejn** [comment]
- [x] 2017/03/05 concurrent transactionsの copy機能を、menu barのFile/download conc log rows に移植 #2
